name: Docker Image CD Stage 2

on:
  push:
    paths:
      - 'release-versions/cardano-node-latest.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Compiling new node software
      run: |      
        docker build . --file files/docker/node/dockerfile_stage2 --compress --tag cardanocommunity/cardano-node:stage2
    - name: docker push stage2
      run: |
        docker push cardanocommunity/cardano-node:stage2
    - name: docker dispatch
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER}}:${{secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/cardano-community/guild-operators/actions/workflows/docker-stage3.yml/dispatches --data '{"ref": "master"}'