name: Docker Image CD Stage 1

on:
  workflow_dispatch:
  push:
    paths:
      - 'files/docker/node/release-versions/guild-prereq-latest.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Compiling new node software
      run: |      
        docker build . --compress --tag cardanocommunity/cardano-node:stage1
    - name: docker push
      run: |
        docker push cardanocommunity/cardano-node:stage1
    - name: docker push
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER}}:${{secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/cardano-community/guild-operators/actions/workflows/docker-stage2.yml/dispatches --data '{"ref": "master"}'
