name: SH Linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shlint:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - name: SH Lint Check
      uses: azohra/shell-linter@latest
      with:
        pattern: "*.sh"
        path: "files/ptn0/scripts,scripts/cnode-helper-scripts" 
